### PR TITLE
Added ability to add custom label formatting for derived classes

### PR DESCRIPTION
**Pull request by dusktreader**
By adding a formatting method to the Element class, a derived class
  can provide its own formatting function. Examples:

```
from goblin.models import Vertex, Edge
import inflection

class CustomVertex(Vertex):

    @classmethod
    def _type_name_formatter(cls, type_name):
        return inflection.camelize(type_name)

class CustomEdge(Edge):

    @classmethod
    def _type_name_formatter(cls, type_name):
        return inflection.underscore(type_name).upper()
```

  Also fixed problem with getting label from Edge classes

### CODE REVIEW

**Comment by jsenecal** [comment]
I'm actually quite happy with the proposed solution and the introduction of the `inflection` package to achieve that. It was more of a design decision to have the labels the way they are and I think using the `inflection` package will help goblin to become more flexible.

Thanks for submitting!

What do you guys think @davebshow and @leifurhauks ?

**Comment by dusktreader** [comment]
FYI, I was having trouble getting the tests to run at all, otherwise I would have tried to introduce a test case to cover them.

**Comment by davebshow** [comment]
I like the idea of being able to control the label formatting, but I'm not sure if overwriting the `_type_name_formatter` is the best approach. I would prefer something simpler probably, like just declaring the label explicitly and in that case, not formatting it:

``` python
class MyVertex(Vertex):
    label = "MyCamelCaseLabel"
```

@leifurhauks your design insight would be appreciated here...

I am fine with `inflection` being added as a dep if needed.

About the tests, yes the are a pain. I'll set up a better way to do it now that we have PRs.

**Comment by leifurhauks** [comment]
This approach with inflector does seem reasonably straightforward. On the other hand, if the app developer knows what the labels should look like, is it really necessary for goblin to generate the labels dynamically? @davebshow 's suggestion has the benefit of being more explicit; the label you see is the the label you get.

**Comment by davebshow** [comment]
My bad, that commit should reference #16.

**Comment by dusktreader** [comment]
Some background: The reason I added the formatter function is because of the code conversion I'm working on now. I'm converting a web server that interacted with neo4j using the py2neo python binding. I had a set of Node and Relationship classes, and I needed them to be able to be constructed from the results of a query. The conversion between class-name and label was crucial, because I used a metaclass factory to construct the correct derived class. I would like to use the same format for Vertex labels and Edge labels as I used for Node labels and Relationship types, and thus I needed a formatter function that I could override in the base Edge and Vertex class for my project.

I will probably have to inject a metaclass factory for my base Edge and Vertex class anyway, so I can probably take care of the label formatting there.

**Comment by davebshow** [comment]
After thinking it over, I would like to merge this PR. Could we change the `_type_name_formatter` method name though? How about something like `format_label`...?

**Comment by dusktreader** [comment]
I changed the name of the formatter to format_type_name because the calling method is type_name not label.

**Comment by davebshow** [comment]
Thanks @dusktreader!

**Pull request merged**
