### PR TITLE
Added support for the equal operator

### PR DESCRIPTION
**Pull request by dusktreader**
This allows edges and vertices to be compared. This is especially
  useful in unit testing so that one can verify that a edge or vertex
  retrieved from the database is the same as an existing instance

### CODE REVIEW

**Comment by davebshow** [comment]
Hi @dusktreader I'm a bit afk today and tomorrow. I'll review this on Friday. Thanks!

**Comment by davebshow** [comment]
As my colleague @leifurhauks pointed out, Django provides a nice example of checking models for equality [1]. Maybe we could do something like (untested):

``` python
    def __eq__(self, other):
        if self.__class__ != other.__class__:
            return False
        if self.id is None:
            return self is other
        return self.id == other.id
```

Also, could you please implement a `__ne__` method and test? Thanks for all your input @dusktreader!
1. https://github.com/django/django/blob/master/django/db/models/base.py#L477

**Comment by dusktreader** [comment]
I'll punch up the **eq** method like you suggested. 

By default, the **ne** operator should just be the **eq** operator results negated. I will add some tests to check that behavior.

**Comment by dusktreader** [comment]
I noticed that there actually was an **eq** operator already. I'm wondering why it didn't seem to work when I decided to add one.

One of the things I noticed is that the old operator compares the values of the two vertices. The new method compares the identities of the two vertices.

Which method do you think should be preferred? Also, is it even possible for Vertices or Edges to not have id attributes?

**Comment by davebshow** [comment]
Ah, so it does. I think the "new" eq implementation is the way to go. 

Yes it is possible. The vertex/edge id is assigned by the db when they are created.

**Comment by dusktreader** [comment]
Branch has been updated and more testing added. I also verified that **ne** is not necessary since, by default, it is just a negatted **eq** operation

**Comment by davebshow** [comment]
Thanks @dusktreader!

**Pull request merged**
